// Auto-generated by labyrinth_preprocessing.py
// Include this file in your OpenSCAD model.

rows = 3;
cols = 3;
target_row = 2;
target_col = 2;

cell_size = 12.0;
wall_thickness = 1.4;
wall_height = 7.0;
ball_diameter = 6.35;
target_hole_diameter = 7.5;

walls_south = [
   [ 1, 0, 0 ],
   [ 0, 1, 0 ],
   [ 1, 1, 1 ]
];

walls_east = [
   [ 0, 1, 1 ],
   [ 1, 0, 1 ],
   [ 0, 0, 1 ]
];

distance_map = [
   [ 4, 3, 2 ],
   [ 3, 2, 1 ],
   [ 2, 1, 0 ]
];

height_map = [
   [ 7.200, 5.700, 4.200 ],
   [ 5.700, 4.200, 2.700 ],
   [ 4.200, 2.700, 1.200 ]
];

flow_direction = [
   [ "E", "S", "S" ],
   [ "S", "E", "S" ],
   [ "E", "E", "T" ]
];
