// ============================================================
// 8x12 Labyrinth Maze
// Sloped floor generated from preprocessed height and flow data
// ============================================================


// ------------------------------------------------------------
// Global settings
// ------------------------------------------------------------

// Thickness of the solid base below the sloped floor.
bottom_thickness = 1;

// Small overlap value used to avoid tiny gaps between walls.
eps = 0.03;

// Local slope strength inside each cell.
// Each cell slopes from height + slope_strength
// to height - slope_strength.
// Example: 0.50 gives 1.00 mm total drop across one cell.
slope_strength = 0.50;

// Set to true for colored slope direction preview.
// Set to false for final STL export if color is not needed.
show_direction_colors = true;

// Resolution for round parts such as the target hole.
$fn = 80;


// ------------------------------------------------------------
// Maze dimensions and physical parameters
// ------------------------------------------------------------

// Auto-generated by labyrinth_preprocessing.py
// This file contains preprocessed maze data for OpenSCAD.

rows = 8;
cols = 12;
target_row = 2;
target_col = 8;

cell_size = 12.0;
wall_thickness = 1.4;
wall_height = 7.0;
ball_diameter = 6.35;
target_hole_diameter = 7.5;

// Highest floor value in height_map.
// Used to create one global wall height.
max_floor_height = 25.200;

// Every wall has this same absolute height from z = 0.
// This prevents walls from having different heights per cell.
wall_total_height = max_floor_height + wall_height;

walls_south = [
   [ 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0 ],
   [ 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0 ],
   [ 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1 ],
   [ 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1 ],
   [ 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1 ],
   [ 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0 ],
   [ 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0 ],
   [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
];

walls_east = [
   [ 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1 ],
   [ 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1 ],
   [ 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1 ],
   [ 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1 ],
   [ 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1 ],
   [ 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1 ],
   [ 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1 ],
   [ 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1 ]
];

distance_map = [
   [ 18, 17, 16, 17, 12, 13, 14, 5, 4, 3, 4, 7 ],
   [ 17, 16, 15, 12, 11, 10, 7, 6, 1, 2, 3, 6 ],
   [ 18, 15, 14, 15, 12, 9, 8, 9, 0, 3, 4, 5 ],
   [ 15, 14, 13, 12, 11, 10, 3, 2, 1, 2, 3, 4 ],
   [ 24, 15, 14, 15, 16, 11, 4, 3, 2, 3, 4, 5 ],
   [ 23, 22, 21, 16, 15, 12, 13, 4, 5, 6, 5, 12 ],
   [ 24, 19, 20, 15, 14, 13, 14, 5, 6, 9, 10, 11 ],
   [ 19, 18, 17, 16, 17, 10, 9, 8, 7, 8, 9, 10 ]
];

height_map = [
   [ 19.200, 18.200, 17.200, 18.200, 13.200, 14.200, 15.200, 6.200, 5.200, 4.200, 5.200, 8.200 ],
   [ 18.200, 17.200, 16.200, 13.200, 12.200, 11.200, 8.200, 7.200, 2.200, 3.200, 4.200, 7.200 ],
   [ 19.200, 16.200, 15.200, 16.200, 13.200, 10.200, 9.200, 10.200, 1.200, 4.200, 5.200, 6.200 ],
   [ 16.200, 15.200, 14.200, 13.200, 12.200, 11.200, 4.200, 3.200, 2.200, 3.200, 4.200, 5.200 ],
   [ 25.200, 16.200, 15.200, 16.200, 17.200, 12.200, 5.200, 4.200, 3.200, 4.200, 5.200, 6.200 ],
   [ 24.200, 23.200, 22.200, 17.200, 16.200, 13.200, 14.200, 5.200, 6.200, 7.200, 6.200, 13.200 ],
   [ 25.200, 20.200, 21.200, 16.200, 15.200, 14.200, 15.200, 6.200, 7.200, 10.200, 11.200, 12.200 ],
   [ 20.200, 19.200, 18.200, 17.200, 18.200, 11.200, 10.200, 9.200, 8.200, 9.200, 10.200, 11.200 ]
];

flow_direction = [
   [ "E", "E", "S", "W", "S", "W", "W", "E", "E", "S", "S", "S" ],
   [ "E", "S", "S", "E", "E", "S", "E", "N", "S", "W", "W", "S" ],
   [ "N", "E", "S", "W", "N", "E", "N", "W", "T", "S", "W", "W" ],
   [ "E", "E", "E", "E", "E", "N", "E", "E", "N", "W", "W", "W" ],
   [ "S", "N", "N", "W", "W", "N", "E", "N", "N", "N", "N", "W" ],
   [ "E", "E", "S", "E", "S", "N", "W", "N", "W", "E", "N", "S" ],
   [ "N", "S", "W", "E", "E", "N", "W", "N", "N", "S", "W", "S" ],
   [ "E", "E", "E", "N", "W", "E", "E", "E", "N", "W", "W", "W" ]
];



// ------------------------------------------------------------
// Helper functions
// ------------------------------------------------------------

// Convert cell column/row index to x/y position.
function x_pos(c) = c * cell_size;
function y_pos(r) = r * cell_size;

// Get height and flow direction of a cell.
function h(r, c) = height_map[r][c];
function dir(r, c) = flow_direction[r][c];

// Optional colors for previewing slope direction.
function dir_color(d) =
    d == "N" ? "lightskyblue" :
    d == "S" ? "lightgreen" :
    d == "E" ? "orange" :
    d == "W" ? "violet" :
    d == "T" ? "red" :
    "lightgray";


// ------------------------------------------------------------
// Direction based flat ramp
// ------------------------------------------------------------

// Each cell is modeled as one flat ramp.
// Its center height comes from height_map.
// The high edge is center height + slope_strength.
// The low edge is center height - slope_strength.
// The low edge points toward flow_direction.

function corner_heights_by_flow(r, c) =
    let(
        center_h = h(r, c),
        high_h = center_h + slope_strength,
        low_h  = center_h - slope_strength,
        d = dir(r, c)
    )

    d == "E" ? [
        high_h, low_h,
        high_h, low_h
    ] :

    d == "W" ? [
        low_h, high_h,
        low_h, high_h
    ] :

    d == "S" ? [
        high_h, high_h,
        low_h, low_h
    ] :

    d == "N" ? [
        low_h, low_h,
        high_h, high_h
    ] :

    [
        center_h, center_h,
        center_h, center_h
    ];


// ------------------------------------------------------------
// Floor tile generation
// ------------------------------------------------------------

// Each cell is one polyhedron.
// Corner order:
// 0 = bottom northwest
// 1 = bottom northeast
// 2 = bottom southwest
// 3 = bottom southeast
// 4 = top northwest
// 5 = top northeast
// 6 = top southwest
// 7 = top southeast

module floor_tile(r, c) {
    x = x_pos(c);
    y = y_pos(r);

    ch = corner_heights_by_flow(r, c);

    color(show_direction_colors ? dir_color(dir(r,c)) : "lightgray")
    polyhedron(
        points = [
            [x,             y,             0],
            [x + cell_size, y,             0],
            [x,             y + cell_size, 0],
            [x + cell_size, y + cell_size, 0],

            [x,             y,             bottom_thickness + ch[0]],
            [x + cell_size, y,             bottom_thickness + ch[1]],
            [x,             y + cell_size, bottom_thickness + ch[2]],
            [x + cell_size, y + cell_size, bottom_thickness + ch[3]]
        ],

        faces = [
            [0, 1, 3, 2],
            [4, 6, 7, 5],
            [0, 4, 5, 1],
            [1, 5, 7, 3],
            [3, 7, 6, 2],
            [2, 6, 4, 0]
        ]
    );
}

module all_floor_tiles() {
    for (r = [0 : rows - 1]) {
        for (c = [0 : cols - 1]) {
            floor_tile(r, c);
        }
    }
}


// ------------------------------------------------------------
// Wall generation
// ------------------------------------------------------------

// All walls start from z = 0 and use wall_total_height.
// This means all walls have the same absolute height.
// The wall height does not depend on the local floor height.

module south_wall(r, c) {
    x = x_pos(c);
    y = y_pos(r + 1) - wall_thickness / 2;

    translate([x - eps, y, 0])
    cube([
        cell_size + 2 * eps,
        wall_thickness,
        wall_total_height
    ]);
}

module east_wall(r, c) {
    x = x_pos(c + 1) - wall_thickness / 2;
    y = y_pos(r);

    translate([x, y - eps, 0])
    cube([
        wall_thickness,
        cell_size + 2 * eps,
        wall_total_height
    ]);
}

module north_boundary_wall(c) {
    x = x_pos(c);
    y = -wall_thickness / 2;

    translate([x - eps, y, 0])
    cube([
        cell_size + 2 * eps,
        wall_thickness,
        wall_total_height
    ]);
}

module west_boundary_wall(r) {
    x = -wall_thickness / 2;
    y = y_pos(r);

    translate([x, y - eps, 0])
    cube([
        wall_thickness,
        cell_size + 2 * eps,
        wall_total_height
    ]);
}

module all_walls() {
    color("dimgray") {
        // The maze data only stores south and east walls.
        // North and west outer boundaries are added separately.

        for (c = [0 : cols - 1]) {
            north_boundary_wall(c);
        }

        for (r = [0 : rows - 1]) {
            west_boundary_wall(r);
        }

        for (r = [0 : rows - 1]) {
            for (c = [0 : cols - 1]) {
                if (walls_south[r][c] == 1) {
                    south_wall(r, c);
                }

                if (walls_east[r][c] == 1) {
                    east_wall(r, c);
                }
            }
        }
    }
}


// ------------------------------------------------------------
// Target hole
// ------------------------------------------------------------

// A vertical hole is cut through the target cell.
// The cut cylinder is taller than the whole model.

module target_hole_cut() {
    x = x_pos(target_col) + cell_size / 2;
    y = y_pos(target_row) + cell_size / 2;

    translate([x, y, -eps])
    cylinder(
        h = wall_total_height + 5,
        d = target_hole_diameter
    );
}


// ------------------------------------------------------------
// Final model
// ------------------------------------------------------------

module labyrinth() {
    difference() {
        union() {
            all_floor_tiles();
            all_walls();
        }

        target_hole_cut();
    }
}

labyrinth();